Repository happbob/oodd-web-react, pull requests merged in 2024-08, with the labels that each got.

#13 Feat: TopBar 공통 컴포넌트 구현
  src/App.tsx
  src/assets/Login/google.png
  src/assets/Login/kakao.png
  src/assets/Login/naver.png
  src/assets/ProfileViewer/Group 87.svg
  src/assets/ProfileViewer/Vector.svg
  src/assets/ProfileViewer/backIcon.svg
  src/assets/ProfileViewer/heart.svg
  src/assets/ProfileViewer/message_send.svg
  src/assets/ProfileViewer/moreIcon.svg
  src/assets/ProfileViewer/star.svg
  src/components/TopBar/dto.ts
  src/components/TopBar/index.tsx
  src/components/TopBar/styles.tsx
  src/pages/Login/components/Google/index.tsx
  src/pages/Login/components/Kakao/index.tsx
  src/pages/Login/components/Naver/index.tsx
  src/pages/Login/components/style.tsx
  src/pages/Login/index.tsx
  src/pages/Login/styles.tsx
  src/pages/ProfileViewer/MocData/index.ts
  src/pages/ProfileViewer/components/PostItem/index.tsx
  src/pages/ProfileViewer/components/PostItem/style.tsx
  src/pages/ProfileViewer/components/UserInfo/index.tsx
  src/pages/ProfileViewer/components/UserInfo/styles.tsx
  src/pages/ProfileViewer/dto.ts
  src/pages/ProfileViewer/index.tsx
  src/pages/ProfileViewer/style.tsx
  src/pages/SignUp/index.tsx
  src/pages/SignUp/style.tsx
  src/pages/Upload/server.cjs
  src/recoil/atoms.ts
Labels: ✨ Feature, 🧑‍🎨 Design

#11 Rename: ComfirmationModal 폴더명 수정
  src/components/ConfirmationModal/dto.ts
  src/components/ConfirmationModal/index.tsx
  src/components/ConfirmationModal/styles.tsx
  src/pages/ConfirmationModalTest/index.tsx
Labels: rename

#14 Feat: BottomSheetMenu에 icon이 없는 메뉴 추가
  src/components/BottomSheetMenu/dto.ts
  src/components/BottomSheetMenu/index.tsx
  src/pages/BottomSheetTest/index.tsx
Labels: ✨ Feature

#16 Refactor: 공통 컴포넌트 디자인 통일 & 바텀시트 사용하지 않는 props 제거
  src/App.tsx
  src/components/BottomSheet/dto.ts
  src/components/BottomSheet/index.tsx
  src/components/BottomSheet/styles.tsx
  src/components/ConfirmationModal/styles.tsx
  src/components/Modal/styles.tsx
  src/pages/BottomSheetTest/Items.tsx
  src/pages/BottomSheetTest/index.tsx
  src/pages/ConfirmationModalTest/index.tsx
  src/pages/Profile/index.tsx
Labels: 🧑‍🎨 Design

#17 Feat: 게시물 수정 기능 구현
  .gitignore
  localhost-key.pem
  localhost.pem
  package.json
  src/apis/core/index.ts
  src/assets/Profile/button_plus.svg
  src/assets/Upload/back.svg
  src/assets/Upload/close.svg
  src/assets/Upload/close2.svg
  src/assets/Upload/clothingTag.svg
  src/assets/Upload/next.svg
  src/assets/Upload/next_up.svg
  src/assets/Upload/picture.svg
  src/assets/Upload/picture2.svg
  src/assets/Upload/pin.svg
  src/assets/Upload/plus.svg
  src/assets/Upload/remove.svg
  src/assets/Upload/styleTag.svg
  src/components/TopBar/styles.tsx
  src/config/constant.ts
  src/pages/Profile/index.tsx
  src/pages/Profile/styles.tsx
  src/pages/Upload/ImageReviewModal/ImageSwiper/index.tsx
  src/pages/Upload/ImageReviewModal/ImageSwiper/styles.tsx
  src/pages/Upload/ImageReviewModal/dto.ts
  src/pages/Upload/ImageReviewModal/index.tsx
  src/pages/Upload/ImageReviewModal/styles.tsx
  src/pages/Upload/ImageSelectModal/dto.ts
  src/pages/Upload/ImageSelectModal/index.tsx
  src/pages/Upload/ImageSelectModal/styles.tsx
  src/pages/Upload/InstaConnectModal/AuthRedirect.tsx
  src/pages/Upload/InstaConnectModal/FailedModal/index.tsx
  src/pages/Upload/InstaConnectModal/FailedModal/styles.tsx
  src/pages/Upload/InstaConnectModal/dto.ts
  src/pages/Upload/InstaConnectModal/index.tsx
  src/pages/Upload/InstaConnectModal/styles.tsx
  src/pages/Upload/InstaFeedSelectModal/dto.ts
  src/pages/Upload/InstaFeedSelectModal/index.tsx
  src/pages/Upload/InstaFeedSelectModal/styles.tsx
  src/pages/Upload/PostUploadModal/ClothingInfoItem/index.tsx
  src/pages/Upload/PostUploadModal/ImageSwiper/index.tsx
  src/pages/Upload/PostUploadModal/ImageSwiper/styles.tsx
  src/pages/Upload/PostUploadModal/SearchBottomSheetContent/index.tsx
  src/pages/Upload/PostUploadModal/SearchBottomSheetContent/styles.tsx
  src/pages/Upload/PostUploadModal/dto.ts
  src/pages/Upload/PostUploadModal/index.tsx
  src/pages/Upload/PostUploadModal/styles.tsx
  src/pages/Upload/dto.ts
  src/pages/Upload/index.tsx
  vite.config.ts
  yarn.lock
Labels: ✨ Feature, 🧑‍🎨 Design

#19 Feat: 채팅 페이지 구현
  package-lock.json
  package.json
  public/ProfileImg.svg
  src/App.css
  src/App.tsx
  src/assets/Chats/Back.svg
  src/assets/Chats/KebabMenu.svg
  src/assets/Chats/Send.svg
  src/context/SocketProvider.tsx
  src/main.tsx
  src/pages/Chats/ChatRoom/ChatBox/index.tsx
  src/pages/Chats/ChatRoom/ChatBox/styles.tsx
  src/pages/Chats/ChatRoom/DateBar/index.tsx
  src/pages/Chats/ChatRoom/DateBar/styles.tsx
  src/pages/Chats/ChatRoom/RcvdMessage/index.tsx
  src/pages/Chats/ChatRoom/RcvdMessage/styles.tsx
  src/pages/Chats/ChatRoom/SentMessage/index.tsx
  src/pages/Chats/ChatRoom/SentMessage/styles.tsx
  src/pages/Chats/ChatRoom/TopBar/index.tsx
  src/pages/Chats/ChatRoom/TopBar/styles.tsx
  src/pages/Chats/ChatRoom/dto.ts
  src/pages/Chats/ChatRoom/index.tsx
  src/pages/Chats/ChatRoom/styles.tsx
  src/pages/Chats/ChatRoomList/index.tsx
  src/pages/Chats/ChatRoomList/styles.tsx
  src/pages/Chats/RecentChat/dto.ts
  src/pages/Chats/RecentChat/index.tsx
  src/pages/Chats/RecentChat/styles.tsx
  src/pages/Chats/Request/index.tsx
  src/pages/Chats/Request/styles.tsx
  src/pages/Chats/TabBar/index.tsx
  src/pages/Chats/TabBar/styles.tsx
  src/pages/Chats/dto.ts
  src/pages/Chats/index.tsx
  src/pages/Chats/styles.tsx
  src/recoil/AllMessages.ts
  src/recoil/MockMessages.ts
  src/recoil/MockUserId.ts
  src/recoil/OpponentInfo.ts
  yarn.lock
Labels: ✨ Feature, 🧑‍🎨 Design

#20 Fix: Chats에서 무한루프에 빠지는 문제 해결
  src/pages/Chats/TabBar/index.tsx
Labels: bug

#24 Fix: id로 수정
  public/ProfileImg 2.svg
  src/assets/Chats/Back 2.svg
  src/assets/Chats/KebabMenu 2.svg
  src/assets/Chats/Send 2.svg
  src/context/SocketProvider 2.tsx
  src/pages/AccountSetting/index.tsx
  src/pages/Mypage/ButtonSecondary/index.tsx
  src/pages/Mypage/index.tsx
  src/pages/PostDetail/dto.tsx
  src/pages/PostDetail/index.tsx
  src/pages/ProfileEdit/index.tsx
  src/pages/SignUp/SignUpDto.ts
  src/pages/SignUp/index.tsx
  src/recoil/AllMessages 2.ts
  src/recoil/MockMessages 2.ts
  src/recoil/MockUserId 2.ts
  src/recoil/OpponentInfo 2.ts
Labels: bug, ✨ Feature, 🧑‍🎨 Design

#26 Feat: 매칭탭 UI & API
  src/assets/Home/casual.svg
  src/assets/Home/classic.svg
  src/assets/Home/feminine.svg
  src/assets/Home/formal.svg
  src/assets/Home/hip.svg
  src/assets/Home/luxury.svg
  src/assets/Home/minimal.svg
  src/assets/Home/outdoor.svg
  src/assets/Home/sporty.svg
  src/assets/Home/street.svg
  src/components/Cards/Card/dto.ts
  src/components/Cards/Card/index.tsx
  src/components/Cards/Card/styles.tsx
  src/pages/Home/OOTD/Tag/index.tsx
  src/pages/Home/OOTD/index.tsx
  src/pages/Home/ReportTextarea.tsx
  src/pages/Home/Tooltip/TooltipBubble/styles.tsx
  src/pages/Home/Tooltip/index.tsx
  src/pages/Home/index.tsx
  src/pages/Post/index.tsx
Labels: ✨ Feature, 📡 API, 🧑‍🎨 Design

#27 Feat: 즐겨찾기 탭 UI & API
  src/App.tsx
  src/components/BottomSheet/index.tsx
  src/components/BottomSheet/styles.tsx
  src/components/Text/StyledText.tsx
  src/pages/Home/Favorites/Feed/index.tsx
  src/pages/Home/Favorites/dto.ts
  src/pages/Home/Favorites/index.tsx
  src/pages/Home/Favorites/styles.tsx
  src/pages/Mypage/index.tsx
  src/pages/Post/ClothingInfoCard.tsx
  src/pages/Post/PostTopBar.tsx
  src/pages/Post/ProductCard.tsx
  src/pages/Post/dto.ts
  src/pages/Post/index.tsx
  src/pages/Post/styles.tsx
  src/pages/Upload/PostUploadModal/ClothingInfoItem/index.tsx
  src/pages/Upload/PostUploadModal/SearchBottomSheetContent/index.tsx
  src/pages/Upload/PostUploadModal/dto.ts
  src/pages/Upload/PostUploadModal/index.tsx
  src/pages/Upload/dto.ts
Labels: ✨ Feature, 📡 API, 🧑‍🎨 Design

#29 Fix: 회원탈퇴 api 수정 및 로딩중 추가
  src/components/NavbarProfile/styles.tsx
  src/pages/AccountCancel/index.tsx
  src/pages/Home/index.tsx
  src/pages/Mypage/index.tsx
  src/pages/Mypage/styles.tsx
Labels: 🐛 Bugfix, ✨ Feature, 📡 API, 🧑‍🎨 Design

#31 Feat: 홈 api 연동
  public/ProfileImg 2.svg
  src/assets/Chats/Back 2.svg
  src/assets/Chats/KebabMenu 2.svg
  src/assets/Chats/Send 2.svg
  src/context/SocketProvider 2.tsx
  src/pages/Home/OOTD/Feed/index.tsx
  src/pages/Home/OOTD/dto.ts
  src/pages/Home/OOTD/index.tsx
  src/pages/Home/OOTD/styles.tsx
  src/pages/Home/index.tsx
  src/pages/Post/index.tsx
Labels: ✨ Feature, 📡 API, 🧑‍🎨 Design

#32 Feat: MyPage + Profile 병합 & MyPost에 게시물 수정 기능 연결
  localhost-key.pem
  localhost.pem
  src/App.tsx
  src/components/BottomSheet/styles.tsx
  src/components/NavbarProfile/styles.tsx
  src/pages/MyPost/assets/DeleteIcon.png
  src/pages/MyPost/assets/EditIcon.svg
  src/pages/MyPost/assets/PinIcon.svg
  src/pages/MyPost/assets/commentIcon.svg
  src/pages/MyPost/assets/heartIcon.svg
  src/pages/MyPost/assets/mockImage.png
  src/pages/MyPost/assets/nextIcon.svg
  src/pages/MyPost/dto.tsx
  src/pages/MyPost/index.tsx
  src/pages/MyPost/styles.tsx
  src/pages/Mypage/index.tsx
  src/pages/Mypage/styles.tsx
  src/pages/Profile/index.tsx
  src/pages/Profile/styles.tsx
  src/pages/ProfileEdit/index.tsx
  src/pages/Upload/PostUploadModal/index.tsx
  src/pages/Upload/index.tsx
Labels: ✨ Feature

#33 Feat: 회원탈퇴 ui 수정
  src/pages/AccountCancel/index.tsx
  src/pages/AccountCancel/styles.tsx
  src/pages/AccountEdit/styles.tsx
Labels: 🧑‍🎨 Design

#34 Feat: 마이 포스트 탑바 수정
  src/pages/MyPost/index.tsx
Labels: 🐛 Bugfix

#35 Feat: 로그인, 회원가입, 프로필 조회 페이지 기능 99% 완료
  .gitignore
  package.json
  src/App.css
  src/apis/core/index.ts
  src/pages/AccountSetting/index.tsx
  src/pages/Home/index.tsx
  src/pages/Login/components/Google/GoogleCallback.tsx
  src/pages/Login/components/Google/index.tsx
  src/pages/Login/components/Kakao/KakaoCallback.tsx
  src/pages/Login/components/Naver/NaverCallback.tsx
  src/pages/Login/components/Naver/index.tsx
  src/pages/Login/components/style.tsx
  src/pages/Login/index.tsx
  src/pages/Mypage/index.tsx
  src/pages/ProfileEdit/index.tsx
  src/pages/ProfileViewer/ResponseDto/UserInfoDto.ts
  src/pages/ProfileViewer/components/PostItem/index.tsx
  src/pages/ProfileViewer/components/ReportText/index.tsx
  src/pages/ProfileViewer/components/RequestComponent/index.tsx
  src/pages/ProfileViewer/components/RequestComponent/style.tsx
  src/pages/ProfileViewer/components/UserInfo/index.tsx
  src/pages/ProfileViewer/dto.ts
  src/pages/ProfileViewer/index.tsx
  src/pages/ProfileViewer/style.tsx
  src/pages/Upload/PostUploadModal/index.tsx
  src/pages/Upload/firebaseConfig.ts
  src/recoil/atoms.ts
  yarn.lock
Labels: 🐛 Bugfix, ✨ Feature, 🧑‍🎨 Design

#36 Feat: 즐겨찾기 탭 api 연결 추가
  src/pages/Home/Favorites/Feed/index.tsx
  src/pages/Home/Favorites/Feed/styles.tsx
  src/pages/Home/Favorites/User/index.tsx
  src/pages/Home/Favorites/User/styles.tsx
  src/pages/Home/Favorites/dto.ts
  src/pages/Home/Favorites/index.tsx
  src/pages/Home/Favorites/styles.tsx
  src/pages/Upload/PostUploadModal/index.tsx
  src/pages/Upload/dto.ts
  src/pages/Upload/index.tsx
Labels: ✨ Feature, 📡 API, 🧑‍🎨 Design

#37 Design: MyPost UI 수정
  src/pages/MyPost/index.tsx
  src/pages/MyPost/styles.tsx
  src/pages/Post/styles.tsx
Labels: 🧑‍🎨 Design

#38 Feat: swiper에 className 추가
  src/pages/Upload/ImageReviewModal/ImageSwiper/index.tsx
  src/pages/Upload/ImageReviewModal/ImageSwiper/styles.tsx
  src/pages/Upload/PostUploadModal/ImageSwiper/index.tsx
  src/pages/Upload/PostUploadModal/ImageSwiper/styles.tsx
Labels: ✨ Feature
